export enum ActionType {
    FETCH_SERIES = "FETCH_SERIES",
    FETCH_SERIES_SUCCESS = "FETCH_SERIES_SUCCESS",
    FETCH_SERIES_ERROR = "FETCH_SERIES_ERROR",

    FETCH_SHOW = "FETCH_SHOW",
    FETCH_SHOW_SUCCESS = "FETCH_SHOW_SUCCESS",
    FETCH_SHOW_ERROR = "FETCH_SHOW_ERROR"
}
